;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
DIGITS  DB 00H
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
START:
        MOV AX, DATA
	MOV DS, AX
	
	;COUNTER 0 SET ,LSB, mod 3 (kare dalga), binary seçildi.
	MOV AL, 00110110B ; mod3
	OUT 9EH, AL ; CW
	;COUNTER 1 SET MSB
	MOV AL, 01110110B ;mod3
	OUT 9EH, AL	
	
	MOV AX,03E8H ; 1000
	OUT 98H,AL ; counter 0 sayma deðerini yükleme
	MOV AL,AH
	OUT 98H,AL
	
	MOV AX,0271H ; 625
	OUT 9AH, AL ; counter 1 sayma deðerini yükleme
	MOV AL,AH
	OUT 9AH, AL
		
	; 1000 625 -> 10mhz saniyede 10^7 tane kare dalga, 16 dalga olmasý için 625 ve 1000 olarak böldüm
	

ENDLESS:

	
        JMP ENDLESS
CODE    ENDS
        END START